spring:
  datasource:
    url: jdbc:postgresql://localhost:5433/rating_system
    username: postgres
    password: postgres
    driver-class-name: org.postgresql.Driver
  data:
    redis:
      host: localhost
      port: 6379
      password:
      timeout: 2000
  jpa:
    hibernate:
      ddl-auto: update
    show-sql: true
    properties:
      hibernate:
        format_sql: true
    database: postgresql
    database-platform: org.hibernate.dialect.PostgreSQLDialect
  jmx:
    enabled: false
logging:
  level:
    root: info
    com.lukaoniani: debug