spring:
  datasource:
    url: jdbc:postgresql://localhost:5432/rating_system
    username: postgres
    password: postgres
    driver-class-name: org.postgresql.Driver
  redis:
    host: localhost
    port: 6379
    password:
    timeout: 2000

#  mail:
#    host: smtp.gmail.com
#    port: 587
#    username: your-email@gmail.com
#    password: your-email-password
#    properties:
#      mail:
#        smtp:
#          auth: true
#          starttls:
#            enable: true
  jpa:
    hibernate:
      ddl-auto: update
    show-sql: true
    properties:
      hibernate:
        format_sql: true
    database: postgresql
    database-platform: org.hibernate.dialect.PostgreSQLDialect
